### PR TITLE
Fixed signatures of Worker::collect() and Pool::collect()

### LINKED ISSUE #836: Worker::collect() should accept any callable, but only accepts \Closure objects
Environment
==========

  * PHP: 7.2.2
  * pthreads: https://github.com/krakjoe/pthreads/commit/2bc44069c1f3c83c866464b60345a333eacee598
  * OS: windows x64

Reproducing Code
==============
```php
function collector(Collectable $collectable) : bool{
	return $collectable->isGarbage();
}

class Work extends \Threaded{
	public function run(){
		sleep(1);
	}
}
$worker = new \Worker();
$worker->start();
$worker->stack(new Work());
while($worker->collect('collector'));
$worker->shutdown();
```

Expected Output
=============
nothing

Actual Output
============
```
Fatal error: Uncaught TypeError: Argument 1 passed to Worker::collect() must be an instance of Closure, string given in pthreads-test.php:38
Stack trace:
#0 pthreads-test.php(38): Worker->collect('collector')
#1 {main}
  thrown in pthreads-test.php on line 38
```

### PR DESCRIPTION
**Pull request by dktapps**
This fixes #836 (incorrect arginfo, again ^.^) - the implementations of these methods accept any callable, but the arginfo demanded Closure objects (break from v2). Since these are documented as accepting `callable`, this should be treated as a bug.

Also fixes Pool::collect()'s optional parameter.

### CODE REVIEW

File: examples/stub.php [hunk 1]
```diff
@@ -452,7 +452,7 @@ public function __construct(int $size, string $class = Worker::class, array $cto
      *
      * @link http://www.php.net/manual/en/pool.collect.php
      */
-    public function collect(callable $collector) {}
+    public function collect(callable $collector = null) {}
```
Comment (tpunt) [inline examples/stub.php]: The default is technically the built-in `Worker::collector` method (same with the `Worker::collect` stub). I'm not sure how it can really be represented in the method signature, though. `[Worker::class, 'collector']` isn't accurate, since it's not a statically callable method, and I'm not sure `[$this, 'collector']` is much better either. Thoughts? Otherwise, perhaps it should just be mentioned in the doc comment instead.

**Comment by tpunt** [comment]
Technical side of the patch looks good to me.

File: examples/stub.php (hunk 1 above)
Comment (dktapps) [reply examples/stub.php]: I wasn't sure on this either. A doc comment is probably the best option.

**Comment by tpunt** [comment]
Merged, thanks!
